### ISSUE TITLE
Provide a bower.json

### ISSUE THREAD

**Issue by mdoelker** [chrisdickinson/raf#29]
Ty :)

**Comment by positlabs** [comment]
Bower can install arbitrary git urls. I'm not sure what the point of providing a bower.json would be, but I'm not super familiar with the internals of bower. What's your reasoning?

**Comment by ljharb** [comment]
It's 2016. Consume things from `npm`.

**Comment by CMTegner** [comment]
To my knowledge, none of the active maintainers use or have knowledge about publishing packages to Bower. If you need a UMD build you can easily grab one from https://wzrd.in/standalone/raf@latest.
