### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by dorsha** [chrisdickinson/raf#36]
At the readme there is:
![image](https://user-images.githubusercontent.com/5429033/33205775-d0460dca-d110-11e7-9423-b61564d0ccb3.png)

But the actual license file is missing.

**Comment by ljharb** [comment]
I don't think the file is actually necessary; https://github.com/chrisdickinson/raf/blob/master/package.json#L22 declares explicitly a license that comes with its own license text already.

**Comment by dorsha** [comment]
It is for automatic libraries that verify license as part of the build process.
Such as: 
https://github.com/ryanuber/go-license
https://github.com/aviadl/thirdPartyLicenseCollector

**Comment by ljharb** [comment]
For npm packages, those libraries should primarily be checking the SPDX-compliant "license" field of `package.json`; if they're not doing that, then they're broken.

**Comment by patricksmms** [comment]
That's right - the license file, with proper copyright, must be present on the repository and npm package (https://tldrlegal.com/license/mit-license). @ljharb

**Comment by patricksmms** [comment]
@ljharb you are probably right. But yet, many companies (like mine) want to play safe so don't allow us to use any code without proper licenses. Would be a shame to have to drop your lib just because of a missing license file. I hope you understand.

**Comment by ljharb** [comment]
It’s not my lib :-)
