### ISSUE TITLE
Add UMD bundle to npm package

### ISSUE THREAD

**Issue by cmwd** [chrisdickinson/raf#38]
Since wzrd.in doesn't work (SSL certificate issue) it's impossible to import raf directly from CDN. It'd be nice to add UMD bundle to npm package, this way we can import lib from unpkg.com - [example](https://unpkg.com/bezier-easing@2.1.0/dist/)

**Comment by ljharb** [comment]
It seems more expedient to get the ssl issue fixed rather than polluting thousands of packages with obsolete module formats, one at a time.

**Comment by CMTegner** [comment]
The certificate has been renewed.
