### ISSUE TITLE
Missing LICENSE file in release tarball.

### ISSUE THREAD

**Issue by ericsnowcurrently** [chrisdickinson/raf#42]
I found your `LICENSE` file at top of the repo.  However, there is no `LICENSE` file in the release tarball (under https://registry.npmjs.org/).  There should be.

**Comment by ljharb** [comment]
Yes there is: https://unpkg.com/raf@3.4.1/LICENSE

**Comment by ericsnowcurrently** [comment]
Ah, we're pinned to 3.4.0.  Thanks.
