### ISSUE TITLE
Why use a calculated delay value 'next' in instead of zero?

### ISSUE THREAD

**Issue by BreakUps** [chrisdickinson/raf#43]
setTimeout(cb, 0) simulates better because delay argument should be as small as to perform callback sooner, while a 10ms delay might skip 2 frame.

**Comment by livelybone** [comment]
Why this closed? I also think 0 is better than 'next'  @chrisdickinson

**Comment by livelybone** [comment]
OK. I realize that I has misunderstand the definition of requestAnimationFrame. It is not equal to requestIdleCallback
